create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  slug text not null unique,
  email text not null unique,
  name text not null,
  handle text not null unique,
  initials text not null,
  location text not null default 'Members Only',
  member_since text not null,
  rating numeric(2,1) not null default 5.0,
  reviews integer not null default 0,
  completed_trades integer not null default 0,
  response_rate text not null default 'New',
  bio text not null default '',
  avatar_seed text not null,
  is_online boolean not null default false,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

alter table public.profiles
  add column if not exists stripe_account_id text,
  add column if not exists stripe_charges_enabled boolean not null default false,
  add column if not exists stripe_payouts_enabled boolean not null default false,
  add column if not exists preferred_payout_provider text not null default 'stripe';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_preferred_payout_provider_check'
  ) then
    alter table public.profiles
      add constraint profiles_preferred_payout_provider_check
      check (preferred_payout_provider in ('stripe', 'paypal', 'wise', 'other'));
  end if;
end $$;

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  tagline text not null default '',
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_archive_pieces (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.brands(id) on delete cascade,
  brand_slug text not null,
  slug text not null,
  title text not null,
  season_kind text not null default 'UNKNOWN'
    check (season_kind in ('SS', 'FW', 'PRE', 'CRUISE', 'UNKNOWN')),
  season_year integer,
  season_label text not null default 'Unknown',
  category text,
  color text,
  cover_image_url text,
  description text[] not null default '{}',
  details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, slug)
);

create index if not exists brand_archive_pieces_brand_slug_idx on public.brand_archive_pieces(brand_slug);
create index if not exists brand_archive_pieces_season_idx on public.brand_archive_pieces(brand_id, season_year desc nulls last, season_kind);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  brand_id bigint references public.brands(id),
  brand text not null,
  brand_slug text not null,
  title text not null,
  subtitle text not null,
  category text not null,
  size text not null,
  condition text not null,
  location text not null,
  price integer not null,
  original_price integer,
  seller_profile_id uuid not null references public.profiles(id) on delete cascade,
  listing_time text not null,
  badge text,
  color text not null,
  description text[] not null default '{}',
  detail_items jsonb not null default '[]'::jsonb,
  source_name text not null,
  source_url text not null,
  moderation_status text not null default 'pending'
    check (moderation_status in ('pending', 'approved', 'denied', 'flagged', 'needs_info')),
  moderation_note text,
  moderation_reviewed_at timestamptz,
  moderation_reviewed_by uuid references public.profiles(id),
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'verified', 'failed', 'needs_review')),
  verification_note text,
  verification_reviewed_at timestamptz,
  verification_reviewed_by uuid references public.profiles(id),
  sold_at timestamptz,
  sold_to_profile_id uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists brand_id bigint references public.brands(id),
  add column if not exists moderation_status text not null default 'pending',
  add column if not exists moderation_note text,
  add column if not exists moderation_reviewed_at timestamptz,
  add column if not exists moderation_reviewed_by uuid references public.profiles(id),
  add column if not exists verification_status text not null default 'unverified',
  add column if not exists verification_note text,
  add column if not exists verification_reviewed_at timestamptz,
  add column if not exists verification_reviewed_by uuid references public.profiles(id),
  add column if not exists sold_at timestamptz,
  add column if not exists sold_to_profile_id uuid references public.profiles(id),
  add column if not exists archive_piece_id bigint references public.brand_archive_pieces(id) on delete set null;

create index if not exists products_archive_piece_id_idx on public.products(archive_piece_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'products_moderation_status_check'
  ) then
    alter table public.products
      add constraint products_moderation_status_check
      check (moderation_status in ('pending', 'approved', 'denied', 'flagged', 'needs_info'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'products_verification_status_check'
  ) then
    alter table public.products
      add constraint products_verification_status_check
      check (verification_status in ('unverified', 'verified', 'failed', 'needs_review'));
  end if;
end $$;

insert into public.brands (slug, name)
select distinct p.brand_slug, p.brand
from public.products p
where p.brand_slug is not null
  and p.brand_slug <> ''
on conflict (slug) do update set name = excluded.name;

update public.products p
set brand_id = b.id
from public.brands b
where p.brand_id is null
  and b.slug = p.brand_slug;

-- Backfill brand_archive_pieces from existing products. Group products by
-- (brand_id, lower(trim(title))) so each unique title becomes one archive
-- piece. The first product image (sort_order, then id) supplies the cover.
with grouped_products as (
  select
    p.brand_id,
    p.brand_slug,
    lower(btrim(p.title)) as normalized_title,
    min(p.id) as first_product_id,
    (array_agg(p.title order by p.id asc))[1] as title,
    (array_agg(p.category order by p.id asc))[1] as category,
    (array_agg(p.color order by p.id asc))[1] as color,
    (array_agg(p.description order by p.id asc))[1] as description,
    (array_agg(p.detail_items order by p.id asc))[1] as detail_items
  from public.products p
  where p.brand_id is not null
  group by p.brand_id, p.brand_slug, normalized_title
)
insert into public.brand_archive_pieces (
  brand_id,
  brand_slug,
  slug,
  title,
  season_kind,
  season_year,
  season_label,
  category,
  color,
  cover_image_url,
  description,
  details
)
select
  gp.brand_id,
  gp.brand_slug,
  regexp_replace(lower(gp.normalized_title), '[^a-z0-9]+', '-', 'g') as slug,
  gp.title,
  'UNKNOWN',
  null,
  'Unknown',
  gp.category,
  gp.color,
  (
    select pi.public_url
    from public.product_images pi
    join public.products p2 on p2.id = pi.product_id
    where lower(btrim(p2.title)) = gp.normalized_title
      and p2.brand_id = gp.brand_id
    order by pi.sort_order asc, p2.id asc
    limit 1
  ),
  coalesce(gp.description, '{}'),
  coalesce(gp.detail_items, '[]'::jsonb)
from grouped_products gp
on conflict (brand_id, slug) do nothing;

update public.products p
set archive_piece_id = bap.id
from public.brand_archive_pieces bap
where p.archive_piece_id is null
  and p.brand_id = bap.brand_id
  and regexp_replace(lower(btrim(p.title)), '[^a-z0-9]+', '-', 'g') = bap.slug;

-- Seed data is approved on import (see scripts/seed-supabase.ts). To promote
-- already-inserted rows after first migrating, run:
--   update public.products set moderation_status = 'approved', verification_status = 'verified';
-- After seeding brands, backfill brand links with:
--   update public.products p set brand_id = b.id from public.brands b where b.slug = p.brand_slug;

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  sort_order integer not null default 0
);

create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete restrict,
  buyer_profile_id uuid not null references public.profiles(id) on delete cascade,
  seller_profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'stripe',
  status text not null default 'pending_checkout'
    check (status in ('pending_checkout', 'awaiting_label', 'label_submitted', 'paid', 'failed', 'canceled', 'refunded')),
  amount integer not null check (amount > 0),
  currency text not null default 'usd',
  platform_fee integer not null default 0 check (platform_fee >= 0),
  checkout_session_id text unique,
  payment_intent_id text,
  label_due_at timestamptz,
  shipping_label_url text,
  shipping_label_storage_path text,
  shipping_label_uploaded_at timestamptz,
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchase_orders_product_id_idx on public.purchase_orders(product_id);
create index if not exists purchase_orders_buyer_profile_id_idx on public.purchase_orders(buyer_profile_id);
create index if not exists purchase_orders_seller_profile_id_idx on public.purchase_orders(seller_profile_id);
create index if not exists purchase_orders_checkout_session_id_idx on public.purchase_orders(checkout_session_id);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('sale_created', 'label_submitted', 'trade_accepted', 'trade_meetup_proposed', 'trade_meetup_agreed', 'trade_completed')),
  purchase_order_id uuid references public.purchase_orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.seller_payout_methods (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('stripe', 'paypal', 'wise', 'other')),
  method_type text not null check (method_type in ('bank_account', 'debit_card', 'wallet', 'other')),
  external_account_id text,
  label text,
  last4 text,
  currency text,
  country text,
  is_default boolean not null default false,
  is_verified boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'active', 'inactive', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, product_id)
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  last_message_preview text not null,
  display_timestamp text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  primary key (conversation_id, profile_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  product_id bigint references public.products(id) on delete set null,
  product_image_url text,
  display_timestamp text not null,
  created_at timestamptz not null default now()
);

alter table public.messages
  add column if not exists product_id bigint references public.products(id) on delete set null,
  add column if not exists product_image_url text;

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  initiator_profile_id uuid not null references public.profiles(id) on delete cascade,
  recipient_profile_id uuid not null references public.profiles(id) on delete cascade,
  status text not null check (status in ('pending', 'accepted', 'declined', 'scheduled', 'completed', 'canceled')),
  message text not null,
  display_timestamp text not null,
  initiator_cash integer,
  recipient_cash integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_items (
  trade_id bigint not null references public.trades(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  side text not null check (side in ('initiator', 'recipient')),
  primary key (trade_id, product_id, side)
);

-- ───────────────────────────── Local in-person trades ─────────────────────────────
-- Post-acceptance meetup + dual-confirmation flow. Money is settled in person
-- (cash or pure barter); no online payments are involved.

-- Approximate, privacy-fuzzed coordinates used only to compute a fair meetup
-- midpoint between two members. Exact home addresses are never stored.
alter table public.profiles
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists location_label text;

alter table public.trades
  add column if not exists completed_at timestamptz;

-- Widen the trades status lifecycle for the meetup flow (idempotent for existing DBs).
do $$
begin
  alter table public.trades drop constraint if exists trades_status_check;
  alter table public.trades
    add constraint trades_status_check
    check (status in ('pending', 'accepted', 'declined', 'scheduled', 'completed', 'canceled'));
end $$;

-- One meetup per trade. The location is chosen from auto-suggested midpoint spots,
-- a curated safe-exchange zone, or a manual pick; both parties must agree, then each
-- independently checks off at the meetup (initiator_/recipient_confirmed_at).
create table if not exists public.trade_meetups (
  id bigint generated by default as identity primary key,
  trade_id bigint not null unique references public.trades(id) on delete cascade,
  status text not null check (status in ('proposed', 'agreed', 'completed', 'canceled')),
  place_name text not null,
  address text,
  latitude double precision not null,
  longitude double precision not null,
  place_source text not null check (place_source in ('auto_suggested', 'curated_safe_zone', 'manual')),
  mapbox_place_id text,
  scheduled_for timestamptz,
  proposed_by_profile_id uuid not null references public.profiles(id) on delete cascade,
  initiator_confirmed_at timestamptz,
  recipient_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Curated, vetted public meetup spots (e.g. police "safe exchange" lots). Seeded.
create table if not exists public.safe_exchange_zones (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  city text,
  latitude double precision not null,
  longitude double precision not null,
  kind text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Notifications can reference a trade (in addition to purchase orders).
alter table public.notifications
  add column if not exists trade_id bigint references public.trades(id) on delete cascade;

do $$
begin
  alter table public.notifications drop constraint if exists notifications_type_check;
  alter table public.notifications
    add constraint notifications_type_check
    check (type in (
      'sale_created', 'label_submitted',
      'trade_accepted', 'trade_meetup_proposed', 'trade_meetup_agreed', 'trade_completed'
    ));
end $$;

create index if not exists trade_meetups_trade_id_idx on public.trade_meetups(trade_id);
create index if not exists notifications_trade_id_idx on public.notifications(trade_id);

-- Foreign-key / RLS hot-path indexes. These columns are filtered on every read
-- of the corresponding list (and scanned by the row-level security policies), so
-- without them Postgres does a sequential scan per query as the tables grow.
create index if not exists products_seller_profile_id_idx on public.products(seller_profile_id);
create index if not exists notifications_profile_id_idx on public.notifications(profile_id);
create index if not exists trades_initiator_profile_id_idx on public.trades(initiator_profile_id);
create index if not exists trades_recipient_profile_id_idx on public.trades(recipient_profile_id);
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);
create index if not exists conversation_participants_profile_id_idx on public.conversation_participants(profile_id);

alter table public.profiles enable row level security;
alter table public.brands enable row level security;
alter table public.brand_archive_pieces enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.seller_payout_methods enable row level security;
alter table public.notifications enable row level security;
alter table public.favorites enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.trades enable row level security;
alter table public.trade_items enable row level security;
alter table public.trade_meetups enable row level security;
alter table public.safe_exchange_zones enable row level security;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
set search_path = public
as $$
  select id from public.profiles where auth_user_id = auth.uid() limit 1
$$;

create or replace function public.current_profile_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select is_admin from public.profiles where auth_user_id = auth.uid() limit 1),
    false
  );
$$;

revoke all on function public.current_profile_is_admin() from public;
grant execute on function public.current_profile_is_admin() to anon;
grant execute on function public.current_profile_is_admin() to authenticated;
grant execute on function public.current_profile_is_admin() to service_role;

-- Used by RLS policies that need "same conversation" checks. A plain EXISTS
-- against public.conversation_participants from another policy on that table
-- causes infinite recursion (PostgreSQL 42P17).
create or replace function public.current_user_participates_in_conversation(p_conversation_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = p_conversation_id
      and cp.profile_id = public.current_profile_id()
  );
$$;

revoke all on function public.current_user_participates_in_conversation(bigint) from public;
grant execute on function public.current_user_participates_in_conversation(bigint) to anon;
grant execute on function public.current_user_participates_in_conversation(bigint) to authenticated;
grant execute on function public.current_user_participates_in_conversation(bigint) to service_role;

drop policy if exists "profiles are public read" on public.profiles;
create policy "profiles are public read"
on public.profiles for select
using (true);

-- The public-read policy above exposes every profile row, so restrict WHICH
-- columns the anonymous (logged-out) role may read. Anonymous clients must not be
-- able to scrape member emails, Stripe payout ids, or raw home coordinates via
-- direct PostgREST. Column-level privileges only take effect once the broad
-- table-level grant is removed, hence revoke-all-then-grant-the-safe-columns.
-- The app's anonymous reads select exactly these columns (PUBLIC_PROFILE_COLUMNS
-- in lib/data/marketplace.ts). Authenticated/service_role reads are unaffected;
-- a member reads their own email/stripe fields as the authenticated role.
revoke select on public.profiles from anon;
grant select (
  id, slug, name, handle, initials, location, member_since, rating, reviews,
  completed_trades, response_rate, bio, avatar_seed, is_online, points
) on public.profiles to anon;

drop policy if exists "brands are public read" on public.brands;
create policy "brands are public read"
on public.brands for select
using (true);

drop policy if exists "brand archive pieces are public read" on public.brand_archive_pieces;
create policy "brand archive pieces are public read"
on public.brand_archive_pieces for select
using (true);

drop policy if exists "brand archive pieces admin write" on public.brand_archive_pieces;
create policy "brand archive pieces admin write"
on public.brand_archive_pieces for all
using (public.current_profile_is_admin())
with check (public.current_profile_is_admin());

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert"
on public.profiles for insert
with check (auth.role() = 'authenticated' and auth.uid() = auth_user_id);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
on public.profiles for update
using (
  auth.role() = 'authenticated'
  and (
    auth.uid() = auth_user_id
    or (auth_user_id is null and lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
  )
)
with check (auth.role() = 'authenticated' and auth.uid() = auth_user_id);

drop policy if exists "products are public read" on public.products;
create policy "products are public read"
on public.products for select
using (true);

drop policy if exists "products owner write" on public.products;
create policy "products owner write"
on public.products for all
using (
  seller_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
)
with check (
  seller_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
);

drop policy if exists "product images are public read" on public.product_images;
create policy "product images are public read"
on public.product_images for select
using (true);

drop policy if exists "product images owner write" on public.product_images;
create policy "product images owner write"
on public.product_images for all
using (
  exists (
    select 1
    from public.products
    where public.products.id = product_images.product_id
      and public.products.seller_profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.products
    where public.products.id = product_images.product_id
      and public.products.seller_profile_id = public.current_profile_id()
  )
);

drop policy if exists "favorites owner read" on public.favorites;
create policy "favorites owner read"
on public.favorites for select
using (profile_id = public.current_profile_id());

drop policy if exists "purchase orders owner read" on public.purchase_orders;
create policy "purchase orders owner read"
on public.purchase_orders for select
using (
  buyer_profile_id = public.current_profile_id()
  or seller_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
);

drop policy if exists "purchase orders buyer insert" on public.purchase_orders;
create policy "purchase orders buyer insert"
on public.purchase_orders for insert
with check (
  buyer_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
);

drop policy if exists "purchase orders participant update" on public.purchase_orders;
create policy "purchase orders participant update"
on public.purchase_orders for update
using (
  buyer_profile_id = public.current_profile_id()
  or seller_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
)
with check (
  buyer_profile_id = public.current_profile_id()
  or seller_profile_id = public.current_profile_id()
  or public.current_profile_is_admin()
);

drop policy if exists "notifications owner read" on public.notifications;
create policy "notifications owner read"
on public.notifications for select
using (profile_id = public.current_profile_id() or public.current_profile_is_admin());

drop policy if exists "notifications owner write" on public.notifications;
create policy "notifications owner write"
on public.notifications for all
using (profile_id = public.current_profile_id() or public.current_profile_is_admin())
with check (profile_id = public.current_profile_id() or public.current_profile_is_admin());

insert into storage.buckets (id, name, public)
values ('shipping-labels', 'shipping-labels', true)
on conflict (id) do nothing;

drop policy if exists "seller payout methods owner read" on public.seller_payout_methods;
create policy "seller payout methods owner read"
on public.seller_payout_methods for select
using (profile_id = public.current_profile_id() or public.current_profile_is_admin());

drop policy if exists "seller payout methods owner write" on public.seller_payout_methods;
create policy "seller payout methods owner write"
on public.seller_payout_methods for all
using (profile_id = public.current_profile_id() or public.current_profile_is_admin())
with check (profile_id = public.current_profile_id() or public.current_profile_is_admin());

drop policy if exists "favorites owner write" on public.favorites;
create policy "favorites owner write"
on public.favorites for all
using (profile_id = public.current_profile_id())
with check (profile_id = public.current_profile_id());

drop policy if exists "conversation participants can read rows" on public.conversation_participants;
create policy "conversation participants can read rows"
on public.conversation_participants for select
using (
  profile_id = public.current_profile_id()
  or public.current_user_participates_in_conversation(conversation_id)
);

drop policy if exists "conversation participants can manage own rows" on public.conversation_participants;
create policy "conversation participants can manage own rows"
on public.conversation_participants for all
using (profile_id = public.current_profile_id())
with check (profile_id = public.current_profile_id());

drop policy if exists "conversation participants can read conversations" on public.conversations;
create policy "conversation participants can read conversations"
on public.conversations for select
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can update conversations" on public.conversations;
create policy "conversation participants can update conversations"
on public.conversations for update
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can insert conversations" on public.conversations;
create policy "conversation participants can insert conversations"
on public.conversations for insert
with check (auth.role() = 'authenticated');

drop policy if exists "conversation participants can read messages" on public.messages;
create policy "conversation participants can read messages"
on public.messages for select
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = messages.conversation_id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can insert messages" on public.messages;
create policy "conversation participants can insert messages"
on public.messages for insert
with check (
  sender_profile_id = public.current_profile_id()
  and exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = messages.conversation_id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "trade participants can read trades" on public.trades;
create policy "trade participants can read trades"
on public.trades for select
using (
  initiator_profile_id = public.current_profile_id()
  or recipient_profile_id = public.current_profile_id()
);

drop policy if exists "trade participants can insert trades" on public.trades;
create policy "trade participants can insert trades"
on public.trades for insert
with check (initiator_profile_id = public.current_profile_id());

-- Trade status transitions (accept / schedule / complete / cancel) are performed
-- exclusively by the server routes using the service-role client, which enforce
-- who may make each transition and in what order. There is intentionally NO
-- client UPDATE policy: a permissive one would let a participant set
-- status='completed' (or accept their own offer) directly via PostgREST with
-- their JWT, bypassing every API-layer guard. With RLS enabled and no UPDATE
-- policy, direct client updates are denied while the service role still writes.
drop policy if exists "trade participants can update trades" on public.trades;

drop policy if exists "trade participants can read trade items" on public.trade_items;
create policy "trade participants can read trade items"
on public.trade_items for select
using (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and (
        public.trades.initiator_profile_id = public.current_profile_id()
        or public.trades.recipient_profile_id = public.current_profile_id()
      )
  )
);

drop policy if exists "trade initiator can manage trade items" on public.trade_items;
create policy "trade initiator can manage trade items"
on public.trade_items for all
using (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and public.trades.initiator_profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and public.trades.initiator_profile_id = public.current_profile_id()
  )
);

-- Trade meetups: either participant of the parent trade can read, propose, agree, and confirm.
drop policy if exists "trade participants can read meetups" on public.trade_meetups;
create policy "trade participants can read meetups"
on public.trade_meetups for select
using (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_meetups.trade_id
      and (
        public.trades.initiator_profile_id = public.current_profile_id()
        or public.trades.recipient_profile_id = public.current_profile_id()
      )
  )
);

-- Meetup proposals, agreements and confirmations are written exclusively by the
-- server routes via the service-role client. Those routes enforce the dual
-- confirmation rule (each caller may set only their OWN confirmation column) and
-- the proposed-by / status gating. There is intentionally NO client INSERT or
-- UPDATE policy: a permissive UPDATE policy would let one participant set BOTH
-- initiator_confirmed_at and recipient_confirmed_at directly via PostgREST,
-- defeating dual-confirmation and unilaterally completing the trade; a permissive
-- INSERT policy would let them spoof proposed_by_profile_id. With RLS enabled and
-- no such policy, direct client writes are denied while the service role still writes.
drop policy if exists "trade participants can insert meetups" on public.trade_meetups;
drop policy if exists "trade participants can update meetups" on public.trade_meetups;

-- Safe exchange zones: public read, admin-only writes.
drop policy if exists "safe exchange zones are public read" on public.safe_exchange_zones;
create policy "safe exchange zones are public read"
on public.safe_exchange_zones for select
using (true);

drop policy if exists "safe exchange zones admin write" on public.safe_exchange_zones;
create policy "safe exchange zones admin write"
on public.safe_exchange_zones for all
using (public.current_profile_is_admin())
with check (public.current_profile_is_admin());

-- Resync identity after INSERT/upsert with explicit `id` (e.g. seed script); otherwise
-- the next DEFAULT id can collide and raise duplicate key on products_pkey.
create or replace function public.sync_products_id_sequence()
returns bigint
language sql
security definer
set search_path = public
as $$
  select setval(
    pg_get_serial_sequence('public.products', 'id'),
    coalesce((select max(id) from public.products), 0),
    true
  );
$$;

revoke all on function public.sync_products_id_sequence() from public;
grant execute on function public.sync_products_id_sequence() to service_role;

-- Resync identity after seeding conversations with explicit ids.
create or replace function public.sync_conversations_id_sequence()
returns bigint
language sql
security definer
set search_path = public
as $$
  select setval(
    pg_get_serial_sequence('public.conversations', 'id'),
    coalesce((select max(id) from public.conversations), 0),
    true
  );
$$;

revoke all on function public.sync_conversations_id_sequence() from public;
grant execute on function public.sync_conversations_id_sequence() to service_role;

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do nothing;

-- Curated safe-exchange meetup spots (reference data). NYC-area seed; grows over time.
create unique index if not exists safe_exchange_zones_name_key on public.safe_exchange_zones (name);

insert into public.safe_exchange_zones (name, address, city, latitude, longitude, kind)
values
  ('NYPD 84th Precinct — Safe Exchange Zone', '301 Gold St, Brooklyn, NY 11201', 'New York', 40.6924, -73.9858, 'police_lot'),
  ('NYPD 94th Precinct — Safe Exchange Zone', '100 Meserole Ave, Brooklyn, NY 11222', 'New York', 40.7237, -73.9501, 'police_lot'),
  ('NYPD 108th Precinct — Safe Exchange Zone', '5-47 50th Ave, Long Island City, NY 11101', 'New York', 40.7407, -73.9499, 'police_lot'),
  ('NYPD Midtown South Precinct — Safe Exchange Zone', '357 W 35th St, New York, NY 10001', 'New York', 40.7530, -73.9942, 'police_lot'),
  ('NYPD 13th Precinct — Safe Exchange Zone', '230 E 21st St, New York, NY 10010', 'New York', 40.7376, -73.9847, 'police_lot'),
  ('Grand Central Terminal — Main Concourse', '89 E 42nd St, New York, NY 10017', 'New York', 40.7527, -73.9772, 'public'),
  ('Brooklyn Public Library — Central Branch', '10 Grand Army Plaza, Brooklyn, NY 11238', 'New York', 40.6722, -73.9681, 'public'),
  ('Queens Center Mall — Guest Services', '90-15 Queens Blvd, Elmhurst, NY 11373', 'New York', 40.7340, -73.8700, 'public')
on conflict (name) do nothing;
