create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  slug text not null unique,
  email text not null unique,
  name text not null,
  handle text not null unique,
  initials text not null,
  location text not null default 'Members Only',
  member_since text not null,
  rating numeric(2,1) not null default 5.0,
  reviews integer not null default 0,
  completed_trades integer not null default 0,
  response_rate text not null default 'New',
  bio text not null default '',
  avatar_seed text not null,
  is_online boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  brand text not null,
  brand_slug text not null,
  title text not null,
  subtitle text not null,
  category text not null,
  size text not null,
  condition text not null,
  location text not null,
  price integer not null,
  original_price integer,
  seller_profile_id uuid not null references public.profiles(id) on delete cascade,
  listing_time text not null,
  badge text,
  color text not null,
  description text[] not null default '{}',
  detail_items jsonb not null default '[]'::jsonb,
  source_name text not null,
  source_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  sort_order integer not null default 0
);

create table if not exists public.favorites (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, product_id)
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  last_message_preview text not null,
  display_timestamp text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  primary key (conversation_id, profile_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  display_timestamp text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  initiator_profile_id uuid not null references public.profiles(id) on delete cascade,
  recipient_profile_id uuid not null references public.profiles(id) on delete cascade,
  status text not null check (status in ('pending', 'accepted', 'declined')),
  message text not null,
  display_timestamp text not null,
  initiator_cash integer,
  recipient_cash integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_items (
  trade_id bigint not null references public.trades(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  side text not null check (side in ('initiator', 'recipient')),
  primary key (trade_id, product_id, side)
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.favorites enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.trades enable row level security;
alter table public.trade_items enable row level security;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
as $$
  select id from public.profiles where auth_user_id = auth.uid() limit 1
$$;

-- Used by RLS policies that need "same conversation" checks. A plain EXISTS
-- against public.conversation_participants from another policy on that table
-- causes infinite recursion (PostgreSQL 42P17).
create or replace function public.current_user_participates_in_conversation(p_conversation_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = p_conversation_id
      and cp.profile_id = public.current_profile_id()
  );
$$;

revoke all on function public.current_user_participates_in_conversation(bigint) from public;
grant execute on function public.current_user_participates_in_conversation(bigint) to anon;
grant execute on function public.current_user_participates_in_conversation(bigint) to authenticated;
grant execute on function public.current_user_participates_in_conversation(bigint) to service_role;

drop policy if exists "profiles are public read" on public.profiles;
create policy "profiles are public read"
on public.profiles for select
using (true);

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert"
on public.profiles for insert
with check (auth.role() = 'authenticated' and auth.uid() = auth_user_id);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
on public.profiles for update
using (
  auth.role() = 'authenticated'
  and (
    auth.uid() = auth_user_id
    or (auth_user_id is null and lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
  )
)
with check (auth.role() = 'authenticated' and auth.uid() = auth_user_id);

drop policy if exists "products are public read" on public.products;
create policy "products are public read"
on public.products for select
using (true);

drop policy if exists "products owner write" on public.products;
create policy "products owner write"
on public.products for all
using (seller_profile_id = public.current_profile_id())
with check (seller_profile_id = public.current_profile_id());

drop policy if exists "product images are public read" on public.product_images;
create policy "product images are public read"
on public.product_images for select
using (true);

drop policy if exists "product images owner write" on public.product_images;
create policy "product images owner write"
on public.product_images for all
using (
  exists (
    select 1
    from public.products
    where public.products.id = product_images.product_id
      and public.products.seller_profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.products
    where public.products.id = product_images.product_id
      and public.products.seller_profile_id = public.current_profile_id()
  )
);

drop policy if exists "favorites owner read" on public.favorites;
create policy "favorites owner read"
on public.favorites for select
using (profile_id = public.current_profile_id());

drop policy if exists "favorites owner write" on public.favorites;
create policy "favorites owner write"
on public.favorites for all
using (profile_id = public.current_profile_id())
with check (profile_id = public.current_profile_id());

drop policy if exists "conversation participants can read rows" on public.conversation_participants;
create policy "conversation participants can read rows"
on public.conversation_participants for select
using (
  profile_id = public.current_profile_id()
  or public.current_user_participates_in_conversation(conversation_id)
);

drop policy if exists "conversation participants can manage own rows" on public.conversation_participants;
create policy "conversation participants can manage own rows"
on public.conversation_participants for all
using (profile_id = public.current_profile_id())
with check (profile_id = public.current_profile_id());

drop policy if exists "conversation participants can read conversations" on public.conversations;
create policy "conversation participants can read conversations"
on public.conversations for select
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can update conversations" on public.conversations;
create policy "conversation participants can update conversations"
on public.conversations for update
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conversations.id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can insert conversations" on public.conversations;
create policy "conversation participants can insert conversations"
on public.conversations for insert
with check (auth.role() = 'authenticated');

drop policy if exists "conversation participants can read messages" on public.messages;
create policy "conversation participants can read messages"
on public.messages for select
using (
  exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = messages.conversation_id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "conversation participants can insert messages" on public.messages;
create policy "conversation participants can insert messages"
on public.messages for insert
with check (
  sender_profile_id = public.current_profile_id()
  and exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = messages.conversation_id
      and cp.profile_id = public.current_profile_id()
  )
);

drop policy if exists "trade participants can read trades" on public.trades;
create policy "trade participants can read trades"
on public.trades for select
using (
  initiator_profile_id = public.current_profile_id()
  or recipient_profile_id = public.current_profile_id()
);

drop policy if exists "trade participants can insert trades" on public.trades;
create policy "trade participants can insert trades"
on public.trades for insert
with check (initiator_profile_id = public.current_profile_id());

drop policy if exists "trade participants can update trades" on public.trades;
create policy "trade participants can update trades"
on public.trades for update
using (
  initiator_profile_id = public.current_profile_id()
  or recipient_profile_id = public.current_profile_id()
)
with check (
  initiator_profile_id = public.current_profile_id()
  or recipient_profile_id = public.current_profile_id()
);

drop policy if exists "trade participants can read trade items" on public.trade_items;
create policy "trade participants can read trade items"
on public.trade_items for select
using (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and (
        public.trades.initiator_profile_id = public.current_profile_id()
        or public.trades.recipient_profile_id = public.current_profile_id()
      )
  )
);

drop policy if exists "trade initiator can manage trade items" on public.trade_items;
create policy "trade initiator can manage trade items"
on public.trade_items for all
using (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and public.trades.initiator_profile_id = public.current_profile_id()
  )
)
with check (
  exists (
    select 1
    from public.trades
    where public.trades.id = trade_items.trade_id
      and public.trades.initiator_profile_id = public.current_profile_id()
  )
);

-- Resync identity after INSERT/upsert with explicit `id` (e.g. seed script); otherwise
-- the next DEFAULT id can collide and raise duplicate key on products_pkey.
create or replace function public.sync_products_id_sequence()
returns bigint
language sql
security definer
set search_path = public
as $$
  select setval(
    pg_get_serial_sequence('public.products', 'id'),
    coalesce((select max(id) from public.products), 0),
    true
  );
$$;

revoke all on function public.sync_products_id_sequence() from public;
grant execute on function public.sync_products_id_sequence() to service_role;

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do nothing;
